-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.product_price
(
    price_id integer NOT NULL DEFAULT nextval('product_price_id_seq'::regclass),
    date date,
    product_id integer,
    price character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT product_price_pkey PRIMARY KEY (price_id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    product_id integer NOT NULL DEFAULT nextval('products_id_seq'::regclass),
    name text COLLATE pg_catalog."default",
    url text COLLATE pg_catalog."default",
    picture_path character varying(256) COLLATE pg_catalog."default",
    coupon character varying(64) COLLATE pg_catalog."default",
    category character varying(64) COLLATE pg_catalog."default",
    phrase character varying(512) COLLATE pg_catalog."default",
    active boolean DEFAULT true,
    CONSTRAINT products_pkey PRIMARY KEY (product_id),
    CONSTRAINT unique_url UNIQUE (url)
);

ALTER TABLE IF EXISTS public.product_price
    ADD CONSTRAINT product_price_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;